[features]
seeds = false
[programs.localnet]
realitycoin_consensus = "9bP6UsBbWu1NQdco93V38CfhhNEracDuGA5VEhWpPXB8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/kyle/.config/solana/id.json"

[scripts]
test = "yarn jest"
